//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace h_store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Annotation
    {
        public int Id { get; set; }
        public string updated { get; set; }
        public string target { get; set; }
        public string created { get; set; }
        public string text { get; set; }
        public string tags { get; set; }
        public string uri { get; set; }
        public string document { get; set; }
        public string consumer { get; set; }
        public string permissions { get; set; }
        public string user { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
